/* Generated by gliss-attr ($(date)) copyright (c) 2009 IRIT - UPS */

#include <$(proc)/api.h>
#include <$(proc)/id.h>
#include <$(proc)/macros.h>
#include <$(proc)/grt.h>

#ifdef __cplusplus
extern "C" {
#endif

elm::t::uint32 op_return;
typedef void (*fun_t)($(proc)_inst_t* inst);
#define SET_OP(x)	op_return = x

/*** function definition ***/

static void xilinx_r5_op_UNKNOWN($(proc)_inst_t* inst) {
	SET_OP(1);
}

$(foreach instructions)
static void xilinx_r5_op_$(IDENT)($(proc)_inst_t* inst) {
	$(arm7_op)
};

$(end)


/*** function table ***/
static fun_t n_op_funs[] = {
	xilinx_r5_op_UNKNOWN$(foreach instructions),
	xilinx_r5_op_$(IDENT)$(end)
};

/**
 * Get the xilinx_r5 op.
 * @return xilinx_r5 op.
 */
elm::t::uint32 xilinx_r5_n_reg(void* _inst) {
	arm_inst_t* inst = static_cast<arm_inst_t*>(_inst);
	n_op_funs[inst->ident](inst);
	return op_return;
}

#ifdef __cplusplus
}
#endif
