/* Generated by gliss-attr ($(date)) copyright (c) 2009 IRIT - UPS */

#include <$(proc)/api.h>
#include <$(proc)/id.h>
#include <$(proc)/macros.h>
#include <$(proc)/grt.h>

#ifdef __cplusplus
extern "C" {
#endif

xilinx_r5_time_t *time_return;
typedef void (*fun_t)($(proc)_inst_t *inst);
#define SET_TIME(x)	time_return = &x

/*** function definition ***/

static void xilinx_r5_time_UNKNOWN($(proc)_inst_t *inst) {
	SET_TIME(time_unknown);
}

$(foreach instructions)
static void xilinx_r5_time_$(IDENT)($(proc)_inst_t *inst) {
$(arm7_time)
};

$(end)


/*** function table ***/
static fun_t time_funs[] = {
	xilinx_r5_time_UNKNOWN$(foreach instructions),
	xilinx_r5_time_$(IDENT)$(end)
};

/**
 * Get the xilinx_r5 timing.
 * @return xilinx_r5 timing.
 */
xilinx_r5_time_t *xilinx_r5_time(void *_inst) {
	arm_inst_t *inst = static_cast<arm_inst_t *>(_inst);
	time_funs[inst->ident](inst);
	return time_return;
}

#ifdef __cplusplus
}
#endif
